name: "Erica Taneja"
title: "Business Intelligence Analyst"
image:
path: "assets/img/Image circle.png"
alt: "Profile Image"
social: 
LinkedIn: "https://www.linkedin.com/in/erica-taneja/"
email: "ericataneja@gmail.com"
theme: jekyll-theme-minimal
